application: jquery-file-upload
version: 2
runtime: go
api_version: go1

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  expiration: '1d'
- url: /.*
  script: _go_app
